### ISSUE TITLE
Why are you using IQTREE?

### ISSUE THREAD

**Issue by ghost** [sdwfrost/pipelign#1]
As I know, IQTREE can not get a good topology for most multiple sequence dataset, I always use RAxML to get ML tree, could you please give me some advice on this, thanks. :)

**Comment by sdwfrost** [comment]
On what basis do you say that 'IQTREE can not get a good topology for most multiple sequence dataset'? Look at e.g. [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5597042/) for an HIV example and [this](https://academic.oup.com/mbe/article/32/1/268/2925592) from the authors of IQTREE.

Personally I use IQTREE as it is quite flexible.

- `-fast`: quick phylogeny
- `-allnni`: more thorough search

It also had automated model selection, benchmarking of multiple cores, and so is well suited for pipelines.

**Comment by ghost** [comment]
@sdwfrost, I tested many dataset using IQTREE, RAxML, PhyML, Garli and the results showed that the rank for topology are: 1 for RAxML,2 for Garli, 3 for PhyML,and 4 for IQTREE.
